### ISSUE TITLE
runtime line number Exception

### ISSUE THREAD

**Issue by jeansorel** [RickStrahl/Westwind.Scripting#4]
Hello Rick 

I'am using the package and it works very well for my purposes

I would like to know if it's possible to trace back the line number of the script that generated an exception when it is executed

if it's not possible ,  can you suggest me the best alternative strategy to trace the origin of a script execution error ?

thanks for your good work

**Comment by RickStrahl** [comment]
There's no reliable way to do this because the way the code is run is that it's injected into a larger program - all the line number would have to be adjusted and the code may not actually look exactly the same as you wrote it because there transformations.

I looked into this when I originally built this and found it was too unreliable to make it a built-in solution.

**Comment by jeansorel** [comment]
I've figured there was a _serious_ reason .
So I divided the code of the called methods into several numbered steps
before executing each step, the number that identifies it is assigned to a variable that returns to the calling method in case of exceptions

For me it is enough to find the errors cause

Thanks again
