### ISSUE TITLE
support for net7

### ISSUE THREAD

**Issue by HausBJB** [RickStrahl/Westwind.Scripting#9]
Hello, how about the support for net7? good work

**Comment by RickStrahl** [comment]
What is the problem exactly? The .NET 6 package should work fine with .NET 7.

**Comment by RickStrahl** [comment]
I suppose the new Roslyn libraries with support for C# 11 :smile:

**Comment by RickStrahl** [comment]
Looks like adding a .NET 7.0 target for the library breaks this library hard due to apparent runtime type changes and the way references are resolved apparently. This is not a small fix, so this will probably take a while to get going.

In the meantime the .NET 6.0 target works fine in 7.0 so that's what you should be using for now and it looks like there are no issue.

**Comment by HausBJB** [comment]
OK thanks,

Yes, it works so far, but there are conflicts, e.g. with the "System.Diagnostics.Process.dll" library.

**Comment by RickStrahl** [comment]
Why would there be a conflict with that? Can you elaborate, please? Those packages should just roll forward to the latest version from the host application of other packages that use something newer.

**Comment by RickStrahl** [comment]
IAC I've added a .NET 7.0 target which required a few small tweaks. But nothing in the way of base libraries other than the newest Roslyn libraries and support for C# 11.

**Comment by HausBJB** [comment]
Hello, yes you are absolutely right. It's another library that expects System.Diagnostics.Process.dll 6.0.0. I apologize for the inconvenience
